### ISSUE TITLE
we are getting a problem while executing,in cell 12 no G is declared and models doesnt saved or use of checkpointer is also wrong ,can you please reply and help us for executing this code.please...

### ISSUE THREAD

**Issue by veertp10** [DhavalTaunk08/Salient_Object_Detection#1]

**Comment by DhavalTaunk08** [comment]
Replace the code from:-

output_saliency_map = gfrn(input_image, ssp_out)
A = tf.Variable(np.random.rand(256,256), dtype='float32', trainable=True)
b = tf.Variable(np.random.rand(256,1), dtype='float32', trainable=True)
output_saliency_map = tf.add(tf.matmul(A, G), b)

to:-

output_saliency_map = gfrn(input_image, ssp_out)
A = tf.Variable(np.random.rand(256,256), dtype='float32', trainable=True)
b = tf.Variable(np.random.rand(256,1), dtype='float32', trainable=True)
output_saliency_map = tf.add(tf.matmul(A, output_saliency_map), b)

This should solve your issue.
